name: CI

on:
  push:
    paths:
      - 'src/**'
      - 'build.vsh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: vlang/v
        
    - uses: actions/checkout@v4
      with:
        path: app

    - name: Build V
      run: make && sudo ./v symlink
      
    - name: MongoDB
      run: sudo apt install -y libmongoc-dev
    - uses: supercharge/mongodb-github-action@1.10.0
    
    - name: Tests
      run: cd app && v build.vsh test
    
    - name: Build
      run: cd app && v build.vsh release